namespace Proje08_HataKontrolu
{
    internal class Program
    {
        static void Main(string[] args)
        {
			try
			{
                // Buraya normalde calısmasını istediğimiz kodları yazıyoruz.
                // Try bloğu herhangi bir hata var mı yok mu kontrol ediliyor.
                // Eğere bir hata oluşuyorsa CATCH bloğuna yönlendiriliyor.
                Console.Write("1.Sayıyı Giriniz. ");
   //             int sayi1 = Convert.ToInt32(Console.ReadLine());
   //             Console.Write("2.Sayıyı Giriniz. ");
   //             int sayi2 = Convert.ToInt32(Console.ReadLine());
   //             int sonuc = Convert.ToByte(sayi1 / sayi2);
   //             Console.WriteLine(sonuc);

   //         }
   //         catch (DivideByZeroException ex)
			//{
   //             Console.WriteLine("Sıfıra bölünme hatası. ");
   //             //Console.WriteLine(ex.Message);
   //         }
             
   //         catch (OverflowException ex)
   //         {
   //             Console.WriteLine("Haddinden fazla değer girdiniz.");
   //         }

   //         catch (Exception ex)
   //         {
   //             Console.WriteLine("Bilinmeyen bir hata oluştu.");
   //         }
   //         finally
   //         {
   //             // Try ya da catch bloklarından hangisi çalılırsa çalışsın,
   //             // her halükarda çalışmasını istediğimiz kodları buraya yazarız.
                
   //             Console.WriteLine("program sona erdi. ");
    //            }
   






        }
    }
}